#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

const PROJECT_ROOT = __DIR__ . '/';
const PROJECT_SOURCE_ROOT = PROJECT_ROOT . 'src/';

require_once PROJECT_ROOT . 'vendor/autoload.php';

echo "\033[36m Hello world \033[0m" . PHP_EOL;
 