version: '3.7'
services:

  php-fpm:
    image: ${REGISTRY}/${INDEX}-php-fpm:${IMAGE_TAG}
    environment:
      ENV: ${ENV}
    volumes:
      - ./:/var/www/html

  php-cli:
    image: ${REGISTRY}/${INDEX}-php-cli:${IMAGE_TAG}
    environment:
      ENV: ${ENV}
    volumes:
      - ./:/app

  nginx:
    image: ${REGISTRY}/${INDEX}-nginx:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
    volumes:
      - ./:/var/www/html